### ISSUE TITLE
Built in Restful services 

### ISSUE THREAD

**Issue by nidabouzid** [activeviam/pivot-spring-boot#23]
When you pull the project you habe some buit in services.
How do you reach the daysLoaded Restful service ?
Are you using
http://localhost:9090/daysLoaded ?
that gives 404
Am I missing something here ?

**Comment by rigsby-chi-activeviam** [comment]
I think that the pull request #18 fixed this problem but it is only in branch 5.8-jdk11.

**Comment by rigsby-chi-activeviam** [comment]
For branch 5.8-jdk8, the fix was included in 0427acdb6cd9cb183c6d1c2c59b48151c0de253c
