### ISSUE TITLE
Content server unreachable 

### ISSUE THREAD

**Issue by nidabouzid** [activeviam/pivot-spring-boot#24]
I cannot connect to the content server by visiting http://localhost:9090/content as I read:
Uncaught (in promise) TypeError: Cannot read property 'serverUrl' of undefined

**Comment by rigsby-chi-activeviam** [comment]
This has been fixed in cf4d6a77a6bda1664ea2c7be435bc5c456b153c5 for 5.8-jdk11 and 66a455d4abb07bbe6e3ac806db7162e8233a9c49 in 5.8-jdk8
