### ISSUE TITLE
Disable ContextValueFilter registration

### ISSUE THREAD

**Issue by SBrown52** [activeviam/pivot-spring-boot#25]
Should take 5 mins to do

**Comment by OPeyrusse** [comment]
With the latest version of the project, I see that the filter is called every time.
If you place a breakpoint into `ContextValueFilter#doFilter` and curl the JWT endpoint - like `curl -u admin:admin -i http://localhost:9090/jwt/rest/v1/token` - you will see the breakpoint hit.
It should only activate for URLs in under _/pivot/*_.

**Comment by OPeyrusse** [comment]
Yet, this is exactly the method documented in Spring Boot [doc](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-disable-registration-of-a-servlet-or-filter), but not working as we think for some reason.

**Comment by SBrown52** [comment]
Hi Olivier,

The filter will still be hit, but the fix was to make sure that it is not hit twice as was previously seen.
As for only hitting certain URLS, we might need to review the ordering on the Spring Security.

Sam

**Comment by OPeyrusse** [comment]
Ok. Thanks for the update. I will then use the same change and look for the methods `addUrlPatterns` and such. See [this post](https://www.baeldung.com/spring-boot-add-filter#1-filter-with-url-pattern).
