### ISSUE TITLE
Upgrade AP version to 5.8.5 and UI version to 4.3.2

### ISSUE THREAD

**Issue by SBrown52** [activeviam/pivot-spring-boot#27]

**Comment by tht-activeviam** [comment]
working on this [branch](https://github.com/activeviam/pivot-spring-boot/tree/tht/27/upgrade-AP-version)

**Comment by tht-activeviam** [comment]
https://github.com/activeviam/pivot-spring-boot/pull/30

**Comment by tht-activeviam** [comment]
PR Closed:
https://github.com/activeviam/pivot-spring-boot/pull/29
https://github.com/activeviam/pivot-spring-boot/pull/30
