### ISSUE TITLE
[5.9] Failed to login from different origin

### ISSUE THREAD

**Issue by tht-activeviam** [activeviam/pivot-spring-boot#41]
In branch 5.9, login will fail if connect from standalone ActiveUI, such as http://localhost:3000 or http://localhost/activeui-starter-4.3.7/?url=http://localhost:9090

The error message is `[401] Not authenticated` and stacktrace was coming from `JwtRestService`.

**Comment by nidabouzid** [comment]
When I used the sandbox security config it worked for me, we need to check the difference, some pieces might be missing.

**Comment by nidabouzid** [comment]
just merged the PR
