### ISSUE TITLE
Logout Error in the branch 6.0_sb3-no_ui_auth

### ISSUE THREAD

**Issue by tht-activeviam** [activeviam/pivot-spring-boot#59]
In [this branch](https://github.com/activeviam/pivot-spring-boot/tree/6.0_sb3-no_ui_auth), we encountered error when logout so that we raise the ticket [UI-9229](https://activeviam.atlassian.net/browse/UI-9229). 
As explained in the ticket, if we following the configuration in the [PR](https://github.com/activeviam/activepivot/pull/10215), it should resolve our issue.

**Comment by obilliard** [comment]
I spent some time looking at this.
I updated the UI ticket with my findings.

**Comment by obilliard** [comment]
I pushed some changes to ensure the index.html page is not cached.
I also fixed the security when using a standalone UI.
Now, we will have to see what they have cooked in 6.1.
